# Use a Node.js base image based on Alpine
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and pnpm-lock.yaml files
COPY package.json pnpm-lock.yaml ./

# Install pnpm globally
RUN npm install -g pnpm

# Install dependencies
RUN pnpm install 

# Copy the rest of the application code
COPY . .

# Build the application
RUN pnpm build

# Expose the API port
EXPOSE 6000

# Set the command to start the API
CMD [ "pnpm", "start" ]
