version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env.prod
    ports:
      - 5432:5432
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6000:6000
    depends_on:
      - db
    env_file:
      - .env.prod
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: >
      sh -c "
        pnpx prisma migrate dev --name init &&
        pnpm start
      "
    restart: always
